apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  namespace: ns1
spec:
  containers:
  - name: echo
    image: busybox
    command: [ "sh", "-c", "echo 'this is echo' && sleep 1h" ]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  namespace: ns2
spec:
  containers:
  - name: echo
    image: busybox
    command: [ "sh", "-c", "echo 'this is echo' && sleep 1h" ]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  namespace: ns3
spec:
  containers:
  - name: echo
    image: busybox
    command: [ "sh", "-c", "echo 'this is echo' && sleep 1h" ]
