apiVersion: v1
kind: Pod
metadata:
  name: demo-1
spec:
  containers:
  - name: demo
    image: nginx
    resources:
      requests:
        cpu: "500m"
        memory: "300Mi"
        hugepages-2Mi: "100Mi"
      limits:
        hugepages-2Mi: "100Mi"
